# Generated by Django 5.1.5 on 2026-01-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer_name', models.CharField(max_length=255)),
                ('referrer_email', models.EmailField(max_length=254)),
                ('referrer_phone', models.CharField(max_length=20)),
                ('referrer_company', models.CharField(blank=True, max_length=255, null=True)),
                ('referred_name', models.CharField(max_length=255)),
                ('referred_email', models.EmailField(max_length=254)),
                ('referred_phone', models.CharField(max_length=20)),
                ('referred_company', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified (Tier 1)'), ('converted', 'Converted (Tier 2)'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
