# Generated by Django 5.1.5 on 2026-01-24 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0002_referral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='date_submitted',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='status',
        ),
    ]
