# Generated by Django 5.1.5 on 2026-01-24 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0003_remove_referral_date_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer_name',
            field=models.CharField(max_length=100),
        ),
    ]
