# Generated by Django 5.1.5 on 2026-01-24 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0004_referral_created_at_alter_referral_referred_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified (Tier 1)'), ('converted', 'Converted (Tier 2)'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
