# Generated by Django 5.1.5 on 2026-01-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0005_referral_date_submitted_referral_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(choices=[('Embedded Engineer', 'Embedded Engineer'), ('Electronics Design Engineer', 'Electronics Design Engineer'), ('Firmware Engineer', 'Firmware Engineer'), ('Mechanical Design Engineer', 'Mechanical Design Engineer'), ('Manufacturing / Operations', 'Manufacturing / Operations'), ('Internship', 'Internship')], max_length=100)),
                ('experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
