# Generated by Django 5.1.5 on 2026-01-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0006_careerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerapplication',
            name='resume',
        ),
    ]
