# Generated by Django 5.1.5 on 2026-01-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0007_remove_careerapplication_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='experience',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
