# Generated by Django 5.1.5 on 2026-01-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0008_alter_careerapplication_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerapplication',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
